
development:
  adapter: postgresql
  encoding: unicode
  database: Storefront_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: Storefront_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: Storefront_production
  pool: 5

